---
title: "In-class Exercise 4"
author: "Wong Zi Qi"
execute:
  warning: false
  message: false
  freeze: true
---

# 1. Getting Started

```{r}
pacman::p_load(haven, SmartEDA, tidyverse, tidymodels, ggridges, ggthemes, colorspace, ggstatsplot, ggdist)
```

```{r}
exam_data <- read_csv("../data/Exam_data.csv")
```

# 2. Plotting

```{r}
ggplot(data = exam_data, aes(x = ENGLISH,y = CLASS)) +
  geom_boxplot()
```

```{r}
ggplot(exam_data, 
       aes(x = ENGLISH, 
           y = CLASS)) +
  geom_density_ridges(
    scale = 3,
    rel_min_height = 0.01,
    bandwidth = 3.4,
    fill = lighten("#7097BB", .3),
    color = "white"
  ) +
  scale_x_continuous(
    name = "English grades",
    expand = c(0, 0)
    ) +
  scale_y_discrete(name = NULL, expand = expansion(add = c(0.2, 2.6))) +
  theme_ridges()
```

```{r}
ggplot(exam_data,
       aes(x = RACE,
           y = ENGLISH)) +
  stat_halfeye(adjust = 0.5,
               justification = -0.2,
               .width = 0,
               point_colout = NA) +
  geom_boxplot(width = .20,
               outlier.shape = NA) +
  stat_dots(side = "left",
            justification = 1.2,
            binwidth = .5,
            dotsize = 2)
```

```{r}
ggbetweenstats(
  data = exam_data,
  x = GENDER,
  y = MATHS,
  type = "np", # non-parametric
  messages = FALSE
)
```
